# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]


jobs:
  deploy:

    runs-on: ubuntu-latest
    environment: release

    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build ruff pygit2 requests pytest
    - name: Check with ruff
      run: |
        ruff check src
    - name: Unit tests
      run: |
        pytest
    - name: Build package
      run: python -m build

    - name: Publish package distributions to PyPI
      # This workflow is a configured trusted publisher on PyPI.
      uses: pypa/gh-action-pypi-publish@release/v1
